data_dir: /home/baiyang/Documents/data/Train_4chArray
sample_rate: 16000
batch_size: 32
model:
  type: diffusion        # or diffusion
  class: DiffusionModel
training:
  epochs: 100
  lr: 1e-4
  kld_weight: 0.001
inference:
  num_samples: 4
duration: 1
